service: automated-grader
frameworkVersion: '3'
provider:
  name: aws
  runtime: nodejs18.x
  region: eu-west-1
  stage: ${opt:stage, 'dev'}
  tracing:
    lambda: true
    apiGateway: true
  iam: ${file(serverless-files/serverless.iam.yaml)}
  ecr:
    images:
      pythonimage:
        path: ./src/functions/python-grader/
      denoimage:
        path: ./src/functions/deno-grader/
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: '1'
    NODE_OPTIONS: '--enable-source-maps --stack-trace-limit=1000'
    DART_QUEUE_URL: 'placeholder-queue-url' #!Ref DartGraderQueue
    DENO_QUEUE_URL: !Ref DenoGraderQueue
    DENO_DIR: '/var/task' # Lambda doesn't have write permission to Deno default cache directory
    HOME: '/tmp' # Lambda doesn't have write permission to node default log directory
    PYTHON_QUEUE_URL: !Ref PythonGraderQueue
plugins:
  - serverless-esbuild
  - serverless-offline
functions: ${file(serverless-files/serverless.functions.yaml)}
resources:
  Resources: ${file(serverless-files/serverless.resources.yaml)}
