PythonGraderQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: python-grader-queue
    VisibilityTimeout: 960
    # Messages will be stored (and retried) up to 2 days
    MessageRetentionPeriod: 172800
    # TODO: Add dead letter queue
    # RedrivePolicy:
    #   maxReceiveCount: 5
    #   deadLetterTargetArn: !GetAtt PythonGraderQueueDLQ.Arn
DenoGraderQueue:
  Type: AWS::SQS::Queue
  Properties:
    QueueName: deno-grader-queue
    VisibilityTimeout: 960
    # Messages will be stored (and retried) up to 2 days
    MessageRetentionPeriod: 172800
GradingTable:
  Type: AWS::DynamoDB::Table
  Properties:
    BillingMode: PAY_PER_REQUEST
    TableName: grading-table
    AttributeDefinitions:
      - AttributeName: requestId
        AttributeType: S
    KeySchema:
      - AttributeName: requestId
        KeyType: HASH
